### ISSUE TITLE
Docker 

### ISSUE THREAD

**Issue by Querela** [internetarchive/heritrix3#360]
I wrote a Docker file for the current version. Maybe you want to look into it and integrate it here.  
It works for me but I only have some simple use-cases (like API tests with python3), so I do not know how it performs under stress. And whether users require more configuration options. (But they could theoretically bind-mount other files if required.)

See Docker-Hub: https://hub.docker.com/r/ekoerner/heritrix

My Dockerfile (currently in private repository, so I can't provide any link, just the content here)
```Dockerfile
FROM alpine:latest AS build

WORKDIR /opt

# download latest version according to:
#   https://github.com/internetarchive/heritrix3/releases/tag/3.4.0-20200518
RUN \
    wget -O heritrix-3.4.0-20200518-dist.zip https://repo1.maven.org/maven2/org/archive/heritrix/heritrix/3.4.0-20200518/heritrix-3.4.0-20200518-dist.zip && \
    unzip heritrix-3.4.0-20200518-dist.zip && \
    rm heritrix-3.4.0-20200518-dist.zip && \
    mv heritrix-3.4.0-20200518 heritrix && \
    chmod u+x heritrix/bin/heritrix

# create a run script because dynamic configuration of credentials
RUN printf '%s\n' \
    '#!/bin/bash' \
    '' \
    'exec ${HERITRIX_HOME}/bin/heritrix -a "${USERNAME}:${PASSWORD}" -b /' \
    '' \
    > heritrix.sh && \
    chmod +x heritrix.sh

# ---------------------------------------------------------------------------

FROM openjdk:11

# copy prebuild files
COPY --from=build /opt/heritrix /opt/heritrix
COPY --from=build /opt/heritrix.sh /opt/

WORKDIR /opt/heritrix

ENV HERITRIX_HOME /opt/heritrix
# let it run in the foreground, required for docker
ENV FOREGROUND true

# standard webport
# NOTE: that the webpage is via HTTPS only available!
EXPOSE 8443

CMD ["/opt/heritrix.sh"]
```

Example `docker-compose.yml` (also on DockerHub currently)
```yml
version: "3.7"
services:

  heritrix:
    build: .
    container_name: "heritrix"
    # TEST: keeps the container running without doing anything (for inspections)
    # entrypoint: bash -c 'while :; do :; done & kill -STOP $$! && wait $$!'
    # env_file: .env
    environment:
      - USERNAME=admin
      - PASSWORD=admin
      # - JAVA_OPTS=-Xmx1024M
    init: true
    ports:
      # if you want to use a .env file with `PORT=8443` for example
      # - ${PORT}:8443
      - 8443:8443
    restart: unless-stopped
    volumes:
      # where jobs will be stored
      - job-files:/opt/heritrix/jobs

volumes:
  job-files:
```
